import dummy from "../../src/assets/images/Dummy.jpg";

export const DummyData = () => {
  return [
    {
      id: 6748,
      name: "Ralph Edwards",
      role: "Account Executive",
      image: dummy,
      phone: "(303) 555-0105",
      added: "8/15/17",
      lastAccess: "6/21/19",
      status: "Inactive",
      excluded: true,
      downloadTrans: false,
      activeTrans: 0,
    },
    {
      id: 6749,
      name: "John Doe",
      image: dummy,
      role: "Sales Manager",
      phone: "(404) 555-0123",
      added: "9/10/18",
      lastAccess: "5/14/20",
      status: "Active",
      excluded: false,
      downloadTrans: true,
      activeTrans: 3,
    },
    {
      id: 6748,
      name: "Ralph Edwards",
      role: "Account Executive",
      image: dummy,
      phone: "(303) 555-0105",
      added: "8/15/17",
      lastAccess: "6/21/19",
      status: "Inactive",
      excluded: true,
      downloadTrans: false,
      activeTrans: 0,
    },
    {
      id: 6749,
      name: "John Doe",
      image: dummy,
      role: "Sales Manager",
      phone: "(404) 555-0123",
      added: "9/10/18",
      lastAccess: "5/14/20",
      status: "Active",
      excluded: false,
      downloadTrans: true,
      activeTrans: 3,
    },
    {
      id: 6748,
      name: "Ralph Edwards",
      role: "Account Executive",
      image: dummy,
      phone: "(303) 555-0105",
      added: "8/15/17",
      lastAccess: "6/21/19",
      status: "Inactive",
      excluded: true,
      downloadTrans: false,
      activeTrans: 0,
    },
    {
      id: 6749,
      name: "John Doe",
      image: dummy,
      role: "Sales Manager",
      phone: "(404) 555-0123",
      added: "9/10/18",
      lastAccess: "5/14/20",
      status: "Active",
      excluded: false,
      downloadTrans: true,
      activeTrans: 3,
    },
    {
      id: 6748,
      name: "Ralph Edwards",
      role: "Account Executive",
      image: dummy,
      phone: "(303) 555-0105",
      added: "8/15/17",
      lastAccess: "6/21/19",
      status: "Inactive",
      excluded: true,
      downloadTrans: false,
      activeTrans: 0,
    },
    {
      id: 6749,
      name: "John Doe",
      image: dummy,
      role: "Sales Manager",
      phone: "(404) 555-0123",
      added: "9/10/18",
      lastAccess: "5/14/20",
      status: "Active",
      excluded: false,
      downloadTrans: true,
      activeTrans: 3,
    },
    {
      id: 6748,
      name: "Ralph Edwards",
      role: "Account Executive",
      image: dummy,
      phone: "(303) 555-0105",
      added: "8/15/17",
      lastAccess: "6/21/19",
      status: "Inactive",
      excluded: true,
      downloadTrans: false,
      activeTrans: 0,
    },
    {
      id: 6749,
      name: "John Doe",
      image: dummy,
      role: "Sales Manager",
      phone: "(404) 555-0123",
      added: "9/10/18",
      lastAccess: "5/14/20",
      status: "Active",
      excluded: false,
      downloadTrans: true,
      activeTrans: 3,
    },
    {
      id: 6748,
      name: "Ralph Edwards",
      role: "Account Executive",
      image: dummy,
      phone: "(303) 555-0105",
      added: "8/15/17",
      lastAccess: "6/21/19",
      status: "Inactive",
      excluded: true,
      downloadTrans: false,
      activeTrans: 0,
    },
    {
      id: 6749,
      name: "John Doe",
      image: dummy,
      role: "Sales Manager",
      phone: "(404) 555-0123",
      added: "9/10/18",
      lastAccess: "5/14/20",
      status: "Active",
      excluded: false,
      downloadTrans: true,
      activeTrans: 3,
    },
    {
      id: 6748,
      name: "Ralph Edwards",
      role: "Account Executive",
      image: dummy,
      phone: "(303) 555-0105",
      added: "8/15/17",
      lastAccess: "6/21/19",
      status: "Inactive",
      excluded: true,
      downloadTrans: false,
      activeTrans: 0,
    },
    {
      id: 6749,
      name: "John Doe",
      image: dummy,
      role: "Sales Manager",
      phone: "(404) 555-0123",
      added: "9/10/18",
      lastAccess: "5/14/20",
      status: "Active",
      excluded: false,
      downloadTrans: true,
      activeTrans: 3,
    },
    {
      id: 6748,
      name: "Ralph Edwards",
      role: "Account Executive",
      image: dummy,
      phone: "(303) 555-0105",
      added: "8/15/17",
      lastAccess: "6/21/19",
      status: "Inactive",
      excluded: true,
      downloadTrans: false,
      activeTrans: 0,
    },
    {
      id: 6749,
      name: "John Doe",
      image: dummy,
      role: "Sales Manager",
      phone: "(404) 555-0123",
      added: "9/10/18",
      lastAccess: "5/14/20",
      status: "Active",
      excluded: false,
      downloadTrans: true,
      activeTrans: 3,
    },
  ];
};
