import dummy from "../../src/assets/images/Dummy.jpg";
import { ChartData } from "./types";

export const DummyData = () => {
  return [
    {
      id: 6748,
      name: "Ralph Edwards",
      role: "Account Executive",
      image: dummy,
      phone: "(303) 555-0105",
      added: "8/15/17",
      lastAccess: "6/21/19",
      status: "Inactive",
      excluded: true,
      downloadTrans: false,
      activeTrans: 0,
    },
    {
      id: 6749,
      name: "John Doe",
      image: dummy,
      role: "Sales Manager",
      phone: "(404) 555-0123",
      added: "9/10/18",
      lastAccess: "5/14/20",
      status: "Active",
      excluded: false,
      downloadTrans: true,
      activeTrans: 3,
    },
    {
      id: 6748,
      name: "Ralph Edwards",
      role: "Account Executive",
      image: dummy,
      phone: "(303) 555-0105",
      added: "8/15/17",
      lastAccess: "6/21/19",
      status: "Inactive",
      excluded: true,
      downloadTrans: false,
      activeTrans: 0,
    },
    {
      id: 6749,
      name: "John Doe",
      image: dummy,
      role: "Sales Manager",
      phone: "(404) 555-0123",
      added: "9/10/18",
      lastAccess: "5/14/20",
      status: "Active",
      excluded: false,
      downloadTrans: true,
      activeTrans: 3,
    },
    {
      id: 6748,
      name: "Ralph Edwards",
      role: "Account Executive",
      image: dummy,
      phone: "(303) 555-0105",
      added: "8/15/17",
      lastAccess: "6/21/19",
      status: "Inactive",
      excluded: true,
      downloadTrans: false,
      activeTrans: 0,
    },
    {
      id: 6749,
      name: "John Doe",
      image: dummy,
      role: "Sales Manager",
      phone: "(404) 555-0123",
      added: "9/10/18",
      lastAccess: "5/14/20",
      status: "Active",
      excluded: false,
      downloadTrans: true,
      activeTrans: 3,
    },
    {
      id: 6748,
      name: "Ralph Edwards",
      role: "Account Executive",
      image: dummy,
      phone: "(303) 555-0105",
      added: "8/15/17",
      lastAccess: "6/21/19",
      status: "Inactive",
      excluded: true,
      downloadTrans: false,
      activeTrans: 0,
    },
    {
      id: 6749,
      name: "John Doe",
      image: dummy,
      role: "Sales Manager",
      phone: "(404) 555-0123",
      added: "9/10/18",
      lastAccess: "5/14/20",
      status: "Active",
      excluded: false,
      downloadTrans: true,
      activeTrans: 3,
    },
    {
      id: 6748,
      name: "Ralph Edwards",
      role: "Account Executive",
      image: dummy,
      phone: "(303) 555-0105",
      added: "8/15/17",
      lastAccess: "6/21/19",
      status: "Inactive",
      excluded: true,
      downloadTrans: false,
      activeTrans: 0,
    },
    {
      id: 6749,
      name: "John Doe",
      image: dummy,
      role: "Sales Manager",
      phone: "(404) 555-0123",
      added: "9/10/18",
      lastAccess: "5/14/20",
      status: "Active",
      excluded: false,
      downloadTrans: true,
      activeTrans: 3,
    },
    {
      id: 6748,
      name: "Ralph Edwards",
      role: "Account Executive",
      image: dummy,
      phone: "(303) 555-0105",
      added: "8/15/17",
      lastAccess: "6/21/19",
      status: "Inactive",
      excluded: true,
      downloadTrans: false,
      activeTrans: 0,
    },
    {
      id: 6749,
      name: "John Doe",
      image: dummy,
      role: "Sales Manager",
      phone: "(404) 555-0123",
      added: "9/10/18",
      lastAccess: "5/14/20",
      status: "Active",
      excluded: false,
      downloadTrans: true,
      activeTrans: 3,
    },
    {
      id: 6748,
      name: "Ralph Edwards",
      role: "Account Executive",
      image: dummy,
      phone: "(303) 555-0105",
      added: "8/15/17",
      lastAccess: "6/21/19",
      status: "Inactive",
      excluded: true,
      downloadTrans: false,
      activeTrans: 0,
    },
    {
      id: 6749,
      name: "John Doe",
      image: dummy,
      role: "Sales Manager",
      phone: "(404) 555-0123",
      added: "9/10/18",
      lastAccess: "5/14/20",
      status: "Active",
      excluded: false,
      downloadTrans: true,
      activeTrans: 3,
    },
    {
      id: 6748,
      name: "Ralph Edwards",
      role: "Account Executive",
      image: dummy,
      phone: "(303) 555-0105",
      added: "8/15/17",
      lastAccess: "6/21/19",
      status: "Inactive",
      excluded: true,
      downloadTrans: false,
      activeTrans: 0,
    },
    {
      id: 6749,
      name: "John Doe",
      image: dummy,
      role: "Sales Manager",
      phone: "(404) 555-0123",
      added: "9/10/18",
      lastAccess: "5/14/20",
      status: "Active",
      excluded: false,
      downloadTrans: true,
      activeTrans: 3,
    },
  ];
};

export const tableHeaders = [
  { text: "Title Officer", arrowIcon: true },
  { text: "Title Office", arrowIcon: true },
  { text: "Title Rep", arrowIcon: true },
  { text: "Title Rep Pct", arrowIcon: true },
  { text: "Open Date", arrowIcon: true },
  { text: "Estimated Closing Date", arrowIcon: true },
  { text: "Closed Date", arrowIcon: true },
  { text: "Contact", arrowIcon: true },
  { text: "Ae Lead Stage", arrowIcon: true },
  { text: "Transaction Type", arrowIcon: true },
  { text: "File Type", arrowIcon: true },
  { text: "Order Number", arrowIcon: true },
  { text: "File Status", arrowIcon: true },
  { text: "Sale Price", arrowIcon: true },
  { text: "Loan Amount", arrowIcon: true },
  { text: "Property Address", arrowIcon: true },
  { text: "Property County", arrowIcon: true },
  { text: "Property State", arrowIcon: true },
  { text: "Escrow Officer", arrowIcon: true },
  { text: "Listing Agent Company", arrowIcon: true },
  { text: "Listing Agent Contact Name", arrowIcon: true },
  { text: "Listing Agent Contact Email", arrowIcon: true },
  { text: "Listing Agent Phone", arrowIcon: true },
  { text: "Selling Agent Company", arrowIcon: true },
  { text: "Selling Agent Contact Name", arrowIcon: true },
  { text: "Selling Agent Contact Email", arrowIcon: true },
  { text: "Selling Agent Phone", arrowIcon: true },
  { text: "Mortgage Broker Company", arrowIcon: true },
  { text: "Mortgage Broker Contact", arrowIcon: true },
  { text: "Mortgage Broker Contact Email", arrowIcon: true },
  { text: "Mortgage Broker Phone", arrowIcon: true },
  { text: "Underwriter", arrowIcon: true },
  { text: "Created At", arrowIcon: true },
];

export const userTableHeaders = [
  { text: "User", arrowIcon: false },
  { text: "Email", arrowIcon: false },
  { text: "Alternative Email", arrowIcon: false },
  { text: "Business Entity", arrowIcon: false },
  { text: "Career Path", arrowIcon: false },
  { text: "Lead Source", arrowIcon: false },
  { text: "AE Commission Threshold", arrowIcon: false },
  { text: "AE Escrow Commission", arrowIcon: false },
  { text: "AE Title Commission", arrowIcon: false },
  { text: "Exclude Challenges Leaderboards", arrowIcon: false },
  { text: "Send Welcome Email", arrowIcon: false },
  { text: "Download Transactions", arrowIcon: false },
  { text: "Notes", arrowIcon: false },
  { text: "Start Date", arrowIcon: false },
  { text: "Created At", arrowIcon: false },
];

export const initialBuyers = [
  {
    id: "1",
    name: "Annette Black",
    address: "4517 Washington Ave. Manchester, Kentucky 39495",
    agent: "Eleanor Pena",
    agentImage: dummy,
    role: "Buyer",
  },
  {
    id: "2",
    name: "Theresa Webb",
    address: "2972 Westheimer Rd. Santa Ana, Illinois 85486",
    agent: "Eleanor Pena",
    agentImage: dummy,
    role: "Buyer",
  },
  {
    id: "3",
    name: "Jane Cooper",
    address: "3517 W. Gray St. Utica, Pennsylvania 57867",
    agent: "Eleanor Pena",
    agentImage: dummy,
    role: "Buyer",
  },
  {
    id: "4",
    name: "Ronald Richards",
    address: "3891 Ranchview Dr. Richardson, California 62639",
    agent: "Eleanor Pena",
    agentImage: dummy,
    role: "Buyer",
  },
  {
    id: "5",
    name: "Savannah Nguyen",
    address: "2715 Ash Dr. San Jose, South Dakota 83475",
    agent: "Eleanor Pena",
    agentImage: dummy,
    role: "Buyer",
  },
  {
    id: "6",
    name: "Cody Fisher",
    address: "4517 Washington Ave. Manchester, Kentucky 39495",
    agent: "Eleanor Pena",
    agentImage: dummy,
    role: "Buyer",
  },
];

export const users = [
  { rank: 1, name: "Wade Warren", count: 34 },
  { rank: 2, name: "John Doe", count: 28 },
  { rank: 3, name: "Jane Smith", count: 25 },
  { rank: 4, name: "Robert Brown", count: 22 },
  { rank: 5, name: "Emily Davis", count: 21 },
];

export const ListingGraphData: ChartData[] = [
  { name: "Segment 1", value: 25, color: "#EC662A" },
  { name: "Segment 2", value: 15, color: "#3B3B3B" },
  { name: "Segment 3", value: 15, color: "#0EA5E9" },
  { name: "Segment 4", value: 20, color: "#F4A51C" },
  { name: "Segment 5", value: 25, color: "#8B6DF2" },
];

export const sampleOrders: any[] = [
  {
    closedDate: "9/1/10",
    order: "6409",
    status: "Closed",
    propertyAddress: "4501 Elgin St, Cactus, Galveston TX",
  },
  {
    closedDate: "8/21/10",
    order: "6176",
    status: "Closed",
    propertyAddress: "8502 Fredonia Rd, Inglewood",
  },
  {
    closedDate: "8/14/10",
    order: "6134",
    status: "Closed",
    propertyAddress: "8502 Fredonia Rd, Inglewood",
  },
  {
    closedDate: "8/27/10",
    order: "6197",
    status: "Closed",
    propertyAddress: "8502 Fredonia Rd, Inglewood",
  },
  {
    closedDate: "8/6/10",
    order: "6071",
    status: "Closed",
    propertyAddress: "8502 Fredonia Rd, Inglewood",
  },
  {
    closedDate: "8/23/10",
    order: "6544",
    status: "Closed",
    propertyAddress: "8502 Fredonia Rd, Inglewood",
  },
  {
    closedDate: "8/14/10",
    order: "6323",
    status: "Closed",
    propertyAddress: "8502 Fredonia Rd, Inglewood",
  },
  {
    closedDate: "7/18/10",
    order: "6510",
    status: "Closed",
    propertyAddress: "8502 Fredonia Rd, Inglewood",
  },
  {
    closedDate: "4/29/10",
    order: "6467",
    status: "Closed",
    propertyAddress: "8502 Fredonia Rd, Inglewood",
  },
  {
    closedDate: "4/21/10",
    order: "G58",
    status: "Closed",
    propertyAddress: "8502 Fredonia Rd, Inglewood",
  },
  {
    closedDate: "7/18/10",
    order: "6510",
    status: "Closed",
    propertyAddress: "8502 Fredonia Rd, Inglewood",
  },
  {
    closedDate: "4/29/10",
    order: "6467",
    status: "Closed",
    propertyAddress: "8502 Fredonia Rd, Inglewood",
  },
  {
    closedDate: "4/21/10",
    order: "G58",
    status: "Closed",
    propertyAddress: "8502 Fredonia Rd, Inglewood",
  },
  {
    closedDate: "7/18/10",
    order: "6510",
    status: "Closed",
    propertyAddress: "8502 Fredonia Rd, Inglewood",
  },
  {
    closedDate: "4/29/10",
    order: "6467",
    status: "Closed",
    propertyAddress: "8502 Fredonia Rd, Inglewood",
  },
  {
    closedDate: "4/21/10",
    order: "G58",
    status: "Closed",
    propertyAddress: "8502 Fredonia Rd, Inglewood",
  },
  {
    closedDate: "7/18/10",
    order: "6510",
    status: "Closed",
    propertyAddress: "8502 Fredonia Rd, Inglewood",
  },
  {
    closedDate: "4/29/10",
    order: "6467",
    status: "Closed",
    propertyAddress: "8502 Fredonia Rd, Inglewood",
  },
  {
    closedDate: "4/21/10",
    order: "G58",
    status: "Closed",
    propertyAddress: "8502 Fredonia Rd, Inglewood",
  },
  {
    closedDate: "7/18/10",
    order: "6510",
    status: "Closed",
    propertyAddress: "8502 Fredonia Rd, Inglewood",
  },
  {
    closedDate: "4/29/10",
    order: "6467",
    status: "Closed",
    propertyAddress: "8502 Fredonia Rd, Inglewood",
  },
  {
    closedDate: "4/21/10",
    order: "G58",
    status: "Closed",
    propertyAddress: "8502 Fredonia Rd, Inglewood",
  },
  {
    closedDate: "7/18/10",
    order: "6510",
    status: "Closed",
    propertyAddress: "8502 Fredonia Rd, Inglewood",
  },
  {
    closedDate: "4/29/10",
    order: "6467",
    status: "Closed",
    propertyAddress: "8502 Fredonia Rd, Inglewood",
  },
  {
    closedDate: "4/21/10",
    order: "G58",
    status: "Closed",
    propertyAddress: "8502 Fredonia Rd, Inglewood",
  },
  {
    closedDate: "7/18/10",
    order: "6510",
    status: "Closed",
    propertyAddress: "8502 Fredonia Rd, Inglewood",
  },
  {
    closedDate: "4/29/10",
    order: "6467",
    status: "Closed",
    propertyAddress: "8502 Fredonia Rd, Inglewood",
  },
  {
    closedDate: "4/21/10",
    order: "G58",
    status: "Closed",
    propertyAddress: "8502 Fredonia Rd, Inglewood",
  },
];
