import dummy from "../../src/assets/images/Dummy.jpg";

export const DummyData = () => {
  return [
    {
      id: 6748,
      name: "Ralph Edwards",
      role: "Account Executive",
      image: dummy,
      phone: "(303) 555-0105",
      added: "8/15/17",
      lastAccess: "6/21/19",
      status: "Inactive",
      excluded: true,
      downloadTrans: false,
      activeTrans: 0,
    },
    {
      id: 6749,
      name: "John Doe",
      image: dummy,
      role: "Sales Manager",
      phone: "(404) 555-0123",
      added: "9/10/18",
      lastAccess: "5/14/20",
      status: "Active",
      excluded: false,
      downloadTrans: true,
      activeTrans: 3,
    },
    {
      id: 6748,
      name: "Ralph Edwards",
      role: "Account Executive",
      image: dummy,
      phone: "(303) 555-0105",
      added: "8/15/17",
      lastAccess: "6/21/19",
      status: "Inactive",
      excluded: true,
      downloadTrans: false,
      activeTrans: 0,
    },
    {
      id: 6749,
      name: "John Doe",
      image: dummy,
      role: "Sales Manager",
      phone: "(404) 555-0123",
      added: "9/10/18",
      lastAccess: "5/14/20",
      status: "Active",
      excluded: false,
      downloadTrans: true,
      activeTrans: 3,
    },
    {
      id: 6748,
      name: "Ralph Edwards",
      role: "Account Executive",
      image: dummy,
      phone: "(303) 555-0105",
      added: "8/15/17",
      lastAccess: "6/21/19",
      status: "Inactive",
      excluded: true,
      downloadTrans: false,
      activeTrans: 0,
    },
    {
      id: 6749,
      name: "John Doe",
      image: dummy,
      role: "Sales Manager",
      phone: "(404) 555-0123",
      added: "9/10/18",
      lastAccess: "5/14/20",
      status: "Active",
      excluded: false,
      downloadTrans: true,
      activeTrans: 3,
    },
    {
      id: 6748,
      name: "Ralph Edwards",
      role: "Account Executive",
      image: dummy,
      phone: "(303) 555-0105",
      added: "8/15/17",
      lastAccess: "6/21/19",
      status: "Inactive",
      excluded: true,
      downloadTrans: false,
      activeTrans: 0,
    },
    {
      id: 6749,
      name: "John Doe",
      image: dummy,
      role: "Sales Manager",
      phone: "(404) 555-0123",
      added: "9/10/18",
      lastAccess: "5/14/20",
      status: "Active",
      excluded: false,
      downloadTrans: true,
      activeTrans: 3,
    },
    {
      id: 6748,
      name: "Ralph Edwards",
      role: "Account Executive",
      image: dummy,
      phone: "(303) 555-0105",
      added: "8/15/17",
      lastAccess: "6/21/19",
      status: "Inactive",
      excluded: true,
      downloadTrans: false,
      activeTrans: 0,
    },
    {
      id: 6749,
      name: "John Doe",
      image: dummy,
      role: "Sales Manager",
      phone: "(404) 555-0123",
      added: "9/10/18",
      lastAccess: "5/14/20",
      status: "Active",
      excluded: false,
      downloadTrans: true,
      activeTrans: 3,
    },
    {
      id: 6748,
      name: "Ralph Edwards",
      role: "Account Executive",
      image: dummy,
      phone: "(303) 555-0105",
      added: "8/15/17",
      lastAccess: "6/21/19",
      status: "Inactive",
      excluded: true,
      downloadTrans: false,
      activeTrans: 0,
    },
    {
      id: 6749,
      name: "John Doe",
      image: dummy,
      role: "Sales Manager",
      phone: "(404) 555-0123",
      added: "9/10/18",
      lastAccess: "5/14/20",
      status: "Active",
      excluded: false,
      downloadTrans: true,
      activeTrans: 3,
    },
    {
      id: 6748,
      name: "Ralph Edwards",
      role: "Account Executive",
      image: dummy,
      phone: "(303) 555-0105",
      added: "8/15/17",
      lastAccess: "6/21/19",
      status: "Inactive",
      excluded: true,
      downloadTrans: false,
      activeTrans: 0,
    },
    {
      id: 6749,
      name: "John Doe",
      image: dummy,
      role: "Sales Manager",
      phone: "(404) 555-0123",
      added: "9/10/18",
      lastAccess: "5/14/20",
      status: "Active",
      excluded: false,
      downloadTrans: true,
      activeTrans: 3,
    },
    {
      id: 6748,
      name: "Ralph Edwards",
      role: "Account Executive",
      image: dummy,
      phone: "(303) 555-0105",
      added: "8/15/17",
      lastAccess: "6/21/19",
      status: "Inactive",
      excluded: true,
      downloadTrans: false,
      activeTrans: 0,
    },
    {
      id: 6749,
      name: "John Doe",
      image: dummy,
      role: "Sales Manager",
      phone: "(404) 555-0123",
      added: "9/10/18",
      lastAccess: "5/14/20",
      status: "Active",
      excluded: false,
      downloadTrans: true,
      activeTrans: 3,
    },
  ];
};

export const tableHeaders = [
  { text: "Title Officer", arrowIcon: true },
  { text: "Title Office", arrowIcon: true },
  { text: "Title Rep", arrowIcon: true },
  { text: "Title Rep Pct", arrowIcon: true },
  { text: "Open Date", arrowIcon: true },
  { text: "Estimated Closing Date", arrowIcon: true },
  { text: "Closed Date", arrowIcon: true },
  { text: "File Type", arrowIcon: true },
  { text: "Order Number", arrowIcon: true },
  { text: "File Status", arrowIcon: true },
  { text: "Sale Price", arrowIcon: true },
  { text: "Loan Amount", arrowIcon: true },
  { text: "Property Address", arrowIcon: true },
  { text: "Property County", arrowIcon: true },
  { text: "Property State", arrowIcon: true },
  { text: "Escrow Officer", arrowIcon: true },
  { text: "Listing Agent Company", arrowIcon: true },
  { text: "Listing Agent Contact Name", arrowIcon: true },
  { text: "Listing Agent Contact Email", arrowIcon: true },
  { text: "Listing Agent Phone", arrowIcon: true },
  { text: "Selling Agent Company", arrowIcon: true },
  { text: "Selling Agent Contact Name", arrowIcon: true },
  { text: "Selling Agent Contact Email", arrowIcon: true },
  { text: "Selling Agent Phone", arrowIcon: true },
  { text: "Mortgage Broker Company", arrowIcon: true },
  { text: "Mortgage Broker Contact", arrowIcon: true },
  { text: "Mortgage Broker Contact Email", arrowIcon: true },
  { text: "Mortgage Broker Phone", arrowIcon: true },
  { text: "Underwriter", arrowIcon: true },
  { text: "Created At", arrowIcon: true },
];

export const userTableHeaders = [
  { text: "User", arrowIcon: false },
  { text: "Email", arrowIcon: false },
  { text: "Alternative Email", arrowIcon: false },
  { text: "Business Entity", arrowIcon: false },
  { text: "Career Path", arrowIcon: false },
  { text: "Lead Source", arrowIcon: false },
  { text: "AE Commission Threshold", arrowIcon: false },
  { text: "AE Escrow Commission", arrowIcon: false },
  { text: "AE Title Commission", arrowIcon: false },
  { text: "Exclude Challenges Leaderboards", arrowIcon: false },
  { text: "Send Welcome Email", arrowIcon: false },
  { text: "Download Transactions", arrowIcon: false },
  { text: "Notes", arrowIcon: false },
  { text: "Start Date", arrowIcon: false },
  { text: "Created At", arrowIcon: false },
];
